import Head from 'next/head';
import { useState, useEffect } from 'react';
import { Heading, VStack, IconButton, useColorMode } from '@chakra-ui/react';
import { FaSun, FaMoon } from 'react-icons/fa';
import TodoList from '../components/TodoList';
import AddTodo from '../components/AddTodo';

export default function Home() {
  const storage = window.localStorage();
  const [todos, setTodos] = useState(
    () => JSON.parse(storage.getItem('todos')) || []
  );

  useEffect(() => {
    localStorage.setItem('todos', JSON.stringify(todos));
  }, [todos]);

  const initialTodos = [
    { id: 1, body: 'wake up' },
    { id: 2, body: 'get money' },
  ];

  function deleteTodo(id) {
    const newTodos = todos.filter((todo) => todo.id !== id);
    setTodos(newTodos);
  }

  function addTodo(newTodo) {
    setTodos([...todos, newTodo]);
  }

  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <div>
      <Head>
        <title>Chakra UI Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <VStack p={4}>
          <IconButton
            icon={colorMode == 'light' ? <FaSun /> : <FaMoon />}
            isRound='true'
            size='lg'
            alignSelf='flex-end'
            onClick={toggleColorMode}
          />
          <Heading
            fontWeight='extrabold'
            size='2xl'
            bgGradient='linear(to-r, red.500, red.200, gray.500)'
            bgClip='text'
            pb={4}
          >
            Todo App
          </Heading>
          <TodoList todos={todos} deleteTodo={deleteTodo} />
          <AddTodo addTodo={addTodo} />
        </VStack>
      </main>
    </div>
  );
}
